### ISSUE TITLE
chatgpt-4o-latest is not yet added

### ISSUE THREAD

**Issue by jvlinsta** [openai/tiktoken#335]

**Comment by nezakoo** [comment]
Hi @jvlinsta , I think you might find my comment here useful: https://github.com/openai/tiktoken/issues/334#issuecomment-2323724350
It works with `tiktoken==0.7.0` version for me

**Comment by futurisold** [comment]
@nezakoo your code uses `gpt-4o-latest`, not `chatgpt-4o-latest` as written in their [documentation](https://platform.openai.com/docs/models/gpt-4o), that's why it's working for you. 

OpenAI should clarify the correct way to use it, either by updating their documentation or by updating their tokenizer.

**Comment by hauntsaninja** [comment]
Fixed in tiktoken 0.8
