### ISSUE TITLE
How to add extra tokens in tiktoken?

### ISSUE THREAD

**Issue by Stanislas0** [openai/tiktoken#9]
Great work! I want to know how can we add customizable extra tokens to tiktoken. Thank you!

**Comment by hauntsaninja** [comment]
You can create your own Encoding object by passing in a dict from token-bytes to the integer token value.
See this: https://github.com/openai/tiktoken/blob/4226a6c008e394bb9fe5de688b1849ca4a88b27f/tiktoken/core.py#L10
You can see examples of the arguments passed to the constructor here: https://github.com/openai/tiktoken/blob/4226a6c008e394bb9fe5de688b1849ca4a88b27f/tiktoken_ext/openai_public.py#L15

**Comment by hauntsaninja** [comment]
If you want to have your own encoding registered so that `tiktoken.get_encoding(...)` works, you can create a new submodule under the `tiktoken_ext` namespace. This ability to extend tiktoken's registry is currently undocumented. See https://github.com/openai/tiktoken/blob/4226a6c008e394bb9fe5de688b1849ca4a88b27f/tiktoken/registry.py#L22

**Comment by Stanislas0** [comment]
Thank you so much for the swift reply! I'll have a try.

**Comment by Ontopic** [comment]
Sorry for "hijacking", this isssue, but feel it is related enough, instead of opening a separate issue.

When looking at https://huggingface.co/docs/tokenizers/api/added-tokens, what would be the best way, to (as much as possible stay in sync with the original tokenizer configs), add special tokens in tiktoken?

As to match, `rstrip`, `lstrip` and `normalized`, for example. Understandable if not all is possible (yet) in tiktoken, but any further recommendations, as to how, move current GPT2 based encoders, with specials tokens, to tiktoken, would be appreciated!

**Comment by hauntsaninja** [comment]
I've added more documentation for this over here: https://github.com/openai/tiktoken#extending-tiktoken
