### ISSUE TITLE
Can tiktoken be utilized with all GPT models?

### ISSUE THREAD

**Issue by yachty66** [openai/tiktoken#95]
I am interested in using tiktoken to preprocess text data for various GPT models, including every single GPT model. Is it possible to use tiktoken with all of these models? If so, are there any specific considerations or configurations needed to ensure compatibility?

**Comment by hauntsaninja** [comment]
Yes, `tiktoken.encoding_for_model` should provide you a tokeniser for the models in OpenAI's API.

If by GPT, you're using that to mean all GPT-like models not necessarily served by OpenAI, then also probably yes, since BPE tokenisation is a common feature of GPT-like models. You'll need to figure out what the right encoding is though.
